# Generated by Django 3.0.9 on 2020-08-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200803_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Date',
            field=models.CharField(max_length=255),
        ),
    ]
