# Generated by Django 3.0.9 on 2020-08-03 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200803_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Desc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Phone',
            new_name='phone',
        ),
    ]
