# Generated by Django 3.0.9 on 2020-08-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_contact_message_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Slug',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
