# Generated by Django 3.0.9 on 2020-08-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200804_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Slug',
            field=models.CharField(max_length=255),
        ),
    ]
