# Generated by Django 3.0.9 on 2020-08-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_blog_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Date',
            field=models.DateTimeField(max_length=255),
        ),
    ]
