# Generated by Django 3.0.9 on 2020-08-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20200804_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='Time',
        ),
        migrations.AlterField(
            model_name='blog',
            name='Date',
            field=models.DateField(max_length=255),
        ),
    ]
